dnl Checking for OpenAL

PKG_CHECK_MODULES([OPENAL], [openal])
PKG_CHECK_MODULES([FREEALUT], [freealut])
AL_CFLAGS="$OPENAL_CFLAGS $FREEALUT_CFLAGS"
AL_LIBS="$OPENAL_LIBS $FREEALUT_LIBS"

AC_SUBST(AL_CFLAGS)
AC_SUBST(AL_LIBS)

